@startuml
title Behavioural System Use Case Diagram for Energy Service Interface
:Home display: as ho
:Distributer Eneregy Resources: as der
':Energy Service Interface: as esi
:Smart Electricity Meter: as sem

rectangle ESI {
    usecase "Collect SEM data" as semcd
    usecase "Collect DER data" as dercd
    ' usecase "Collect appliences data" as appcd
    usecase "Collect Consumption Control Data" as ccd
    usecase "Process data" as pd
    usecase "Decide on Energy Source usage" as deosu
    usecase "Decide on energy on/offloading" as deo
    usecase "Send energy on/offloading data" as seod
    usecase "Send energy source usage data" as sesud
}

'Actors
' ho -d- appcd
sem -d- semcd
der -d- dercd
ho -d- ccd
der -d- ccd

ccd <-.. pd : <<includes>>
' appcd <-- pd : <<includes>>
semcd <.. pd : <<includes>>
dercd <.. pd : <<includes>>

pd <.. deosu : <<includes>>
pd <.. deo : <<includes>>

seod ..> deo : <<includes>>
sesud ..> deosu : <<includes>>

der -l[hidden]- sem
' footer Secure Software Modelling, Group TRR
@enduml